### PR TITLE
Added a LongColumn.

### PR DESCRIPTION
**Pull request by plaeremans**
I wanted to use the DataFrame, but It couldn't handle Long values, so I implemented this.
Would you be so kind to merge this or give me feedback on what I could improve.

Thanks for your work.

### CODE REVIEW

**Comment by netzwerg** [comment]
Thanks a lot for your contribution – it looks very good. I will do a thorough review & merge asap...

**Comment by netzwerg** [comment]
I merged your changes after making minor modifications. Most importantly, I removed "Copyright Genomics Core" from your class documentation. I will change the generic file headers to give all contributors proper credit (#31) but I don't want to make things complicated with per-file-copyright statements.

Please let me know if you are fine with this strategy, so I can make an official paleo 0.10 release including your contribution.

Thanks again for your help!

**Comment by plaeremans** [comment]
Thanks very much. Sorry about the copy right. it 's an  IntelliJ template :-(. And I'm used to it so I don't notice the copyright.  Glad to have contributed. Thanks for the library!

**Comment by netzwerg** [comment]
Thanks, v0.10.0 includes your contribution and is now officially released!

**Pull request closed without merging**
